### ISSUE TITLE
Can't install Package on my YunoHost Server.

### ISSUE THREAD

**Issue by PerformanceCraft** [YunoHost-Apps/lxd_ynh#56] opened 2022-10-16 17:01 UTC
I can't install the Package on my YunoHost Server. I've already uninstalled Busybox as mentioned in another Thread. Attached the Link for more Information. Thank's in advance.
[url](https://paste.yunohost.org/raw/ojobokiped)

**Comment by Tagadda** [comment] 2023-01-06 11:14
I had the same issue and as said above installing `busybox-static` before installing the app fixed this

**Comment by steepdawn974** [comment] 2023-02-10 11:57
More dependency errors.


### Env:
```
args:
  app: lxd
  force: false
  label: LXD
  no_remove_on_failure: false
ended_at: 2023-02-10 11:50:09.839866
env:
  YNH_APP_ACTION: install
  YNH_APP_BASEDIR: /var/cache/yunohost/app_tmp_work_dirs/app_4cm9ton6
  YNH_APP_ID: lxd
  YNH_APP_INSTANCE_NAME: lxd
  YNH_APP_INSTANCE_NUMBER: '1'
  YNH_APP_MANIFEST_VERSION: 5.10~ynh1
  YNH_APP_PACKAGING_FORMAT: '1.0'
  YNH_ARCH: amd64
error: An error occurred inside the app installation script
interface: api
operation: app_install
parent: null
related_to:
- - app
  - lxd
started_at: 2023-02-10 11:50:02.144020
success: false
yunohost_version: 11.1.6.1```


### Error
```
The following packages have unmet dependencies:
2023-02-10 11:50:08,258: DEBUG -  btrfs-progs : Depends: liblzo2-2 (>= 2.02) but it is not going to be installed
2023-02-10 11:50:08,258: DEBUG -  dmeventd : Depends: liblvm2cmd2.03 (>= 2.03.11) but it is not going to be installed
2023-02-10 11:50:08,258: DEBUG -  lxc : Depends: bridge-utils but it is not going to be installed
2023-02-10 11:50:08,258: DEBUG -        Recommends: debootstrap but it is not going to be installed
2023-02-10 11:50:08,258: DEBUG -        Recommends: libpam-cgfs but it is not going to be installed
2023-02-10 11:50:08,259: DEBUG -        Recommends: lxcfs (>= 3.0.2-1) but it is not going to be installed
2023-02-10 11:50:08,259: DEBUG -        Recommends: lxc-templates (>= 3.0.2-1) but it is not going to be installed
2023-02-10 11:50:08,259: DEBUG -        Recommends: uidmap but it is not going to be installed
2023-02-10 11:50:08,259: DEBUG -  squashfs-tools : Depends: liblzo2-2 (>= 2.02) but it is not going to be installed
2023-02-10 11:50:08,259: DEBUG -  tcl8.6 : Depends: libtcl8.6 (>= 8.6.0) but it is not going to be installed
2023-02-10 11:50:08,259: DEBUG - + ynh_die '--message=Unable to install dependencies'
``` 

Full Log: https://paste.yunohost.org/raw/fokoyeqaqe

**Comment by Salamandar** [comment] 2024-02-02 14:11
duplicate of #84

**Closed by Salamandar** 2024-02-02 14:11 UTC

**Comment by MohamedElashri** [comment] 2024-02-03 01:57
> duplicate of #84
How would #45 and #56 became duplicates of #84 when this one precede the other with more than year ?
