### ISSUE TITLE
Unable to install : liblvm2cmd2.03

### ISSUE THREAD

**Issue by jarod5001** [YunoHost-Apps/lxd_ynh#45] opened 2022-06-18 23:19 UTC
yunohost_version: 4.3.6.3
YNH_ARCH: amd64
Hardware : old laptop at home, nothing special. 
Log : https://paste.yunohost.org/raw/yoqosoqako

Most notable errors : 

```
2022-06-18 23:05:54,387: DEBUG - 0 upgraded, 32 newly installed, 1 to remove and 1 not upgraded.
2022-06-18 23:05:54,388: DEBUG - E: Packages need to be removed but remove is disabled.

```
```
2022-06-18 23:05:55,381: DEBUG - The following packages have unmet dependencies:
2022-06-18 23:05:55,382: DEBUG -  dmeventd : Depends: liblvm2cmd2.03 (>= 2.03.02) but it is not going to be installed
```
And
```
admin@home ~> sudo apt list | grep lvm2cmd       
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

liblvm2cmd2.03/oldstable 2.03.02-3 amd64
``` 
I don't know if I manually install it is recommended.

**Comment by yalh76** [comment] 2022-08-14 23:34
you should remove `busybox` first, that's the issue

**Comment by Salamandar** [comment] 2024-02-02 14:11
Duplicate of #84

**Closed by Salamandar** 2024-02-02 14:11 UTC
